name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    steps:
    - uses: actions/checkout@master
    - name: Set release version
      run: echo "RELEASE_VERSION=$GITHUB_SHA" >> $GITHUB_ENV
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sundowndev/phoneinfoga
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,v2,stable,${{ env.RELEASE_VERSION }}"

    - name: Install yaml processor
      run: |
        wget https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -O ./yq
        chmod +x ./yq

    - name: Commit new tag
      run: |
        ./yq w ./.deploy/deployment.yaml 'spec.template.spec.containers[0].image' sundowndev/phoneinfoga:${{ env.RELEASE_VERSION }} -i
        git remote set-url origin https://${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.GITHUB_USER }}/PhoneInfoga.git
        git config --global user.email "${{ secrets.GITHUB_USER }}@users.noreply.github.com"
        git config --global user.name "${{ secrets.GITHUB_USER }}"
        git add ./.deploy && git commit -m "deploy: updating docker tag [skip ci]"
        git pull origin master --rebase
        git push origin master
