name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[action]') == false
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          push: true
          tags: sundowndev/phoneinfoga:latest,sundowndev/phoneinfoga:v2,sundowndev/phoneinfoga:stable
          platforms: linux/amd64,linux/arm/v7,linux/arm64

      - uses: actions/checkout@v2.3.5
        with:
          ref: 'master'

      - name: Commit new image digest
        env:
          GITHUB_USER: sundowndev
          GITHUB_REPO: PhoneInfoga
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -O ./yq
          chmod +x ./yq
          ./yq w ./.deploy/deployment.yaml 'spec.template.spec.containers[0].image' sundowndev/phoneinfoga@${{ steps.docker_build.outputs.digest }} -i
          git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/$GITHUB_REPO.git
          git config --global user.email "$GITHUB_USER@users.noreply.github.com"
          git config --global user.name "$GITHUB_USER"
          git add ./.deploy && git commit -m "deploy: update docker image digest [action]"
          git pull origin master --rebase
          git push origin master
