name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: sundowndev/phoneinfoga
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,v2,stable"

      - name: Install yaml processor
        run: |
          wget https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -O ./yq
          chmod +x ./yq

      - name: Commit new tag
        run: |
          ./yq w ./.deploy/deployment.yaml 'spec.template.spec.containers[0].image' ${{ steps.publish.outputs.digest }} -i
          git remote set-url origin https://${{ secrets.GH_USER }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.GH_USER }}/PhoneInfoga.git
          git config --global user.email "${{ secrets.GH_USER }}@users.noreply.github.com"
          git config --global user.name "${{ secrets.GH_USER }}"
          git add ./.deploy && git commit -m "deploy: updating docker tag [skip ci]"
          git pull origin master --rebase
          git push origin master
