name: release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 15.11.x

      - name: Building static assets
        run: (cd client && yarn && yarn build)

      - name: Set up Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.16.x

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[action]') == false
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: sundowndev/phoneinfoga:latest,sundowndev/phoneinfoga:v2,sundowndev/phoneinfoga:stable
          platforms: linux/amd64 # ,linux/arm/v7,linux/arm64 - TODO(sundowndev): enable arm support back

      - uses: actions/checkout@v3.0.0
        with:
          ref: 'master'

      - name: Commit new image digest
        env:
          GITHUB_USER: sundowndev
          GITHUB_REPO: PhoneInfoga
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -O ./yq
          chmod +x ./yq
          ./yq w ./.deploy/deployment.yaml 'spec.template.spec.containers[0].image' sundowndev/phoneinfoga@${{ steps.docker_build.outputs.digest }} -i
          git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/$GITHUB_REPO.git
          git config --global user.email "$GITHUB_USER@users.noreply.github.com"
          git config --global user.name "$GITHUB_USER"
          git add ./.deploy && git commit -m "deploy: update docker image digest [action]"
          git pull origin master --rebase
          git push origin master
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set up Python 3.8
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.2.3 mkdocs-material==8.1.4 mkdocs-minify-plugin==0.5.0

      - name: Deploy
        run: |
          git remote set-url origin https://${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.GITHUB_USER }}/phoneinfoga.git
          git config --global user.email "${{ secrets.GITHUB_USER }}@users.noreply.github.com"
          git config --global user.name "${{ secrets.GITHUB_USER }}"
          mkdocs gh-deploy --force
